name: CI Pipeline
on:
  pull_request:
    branches: [ main ]
jobs: 
  run_unit_tests_integration:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven  
      - name: Run unit tests
        run: mvn test -Dtest=CalculatorControllerCalculationTests
  run_code_coverage_integration:
    runs-on: ubuntu-latest
    needs: run_unit_tests_integration
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Generate target folder
        run: mvn test -Dtest=CalculatorControllerCalculationTests
      - name: Calculate code coverage
        run: mvn jacoco:report "-DskipTests" "-Ddependency-check.skip=true"
      - name: run commands
        run: ls -la
        shell: bash
      - name: Upload code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: target/site/jacoco/
          retention-days: 7